name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4
      id: setup-toolchain-jdk
      with:
        distribution: temurin
        java-version: 11
    - uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4
      id: setup-gradle-jdk
      with:
        distribution: temurin
        java-version: 21
    - uses: gradle/actions/setup-gradle@16bf8bc8fe830fa669c3c9f914d3eb147c629707 # v4
    - shell: bash
      env:
        JDK11: ${{ steps.setup-toolchain-jdk.outputs.path }}
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      run: |
        ./gradlew \
        -Porg.gradle.java.installations.auto-download=false \
        javaToolchains \
        ${{ inputs.arguments }}
